### ISSUE TITLE
Submodules cannot be git cloned, permission issue

### ISSUE THREAD

**Issue by cthoma** [ColinKennedy/cursor-text-objects.nvim#7]
### Did you read the documentation and check existing issues?

- [X] I have read all the [`:help cursor-text-objects`](https://github.com/ColinKennedy/cursor-text-objects.nvim/blob/main/doc/my-template-docs.txt) documentation
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the [existing issues](https://github.com/ColinKennedy/cursor-text-objects.nvim/issues) and [closed issues](https://github.com/ColinKennedy/cursor-text-objects.nvim/issues?q=is%3Aissue+is%3Aclosed) issues

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Linux

### Describe the bug

Adding recommended plugin setup to lazy.nvim

```
{
    "ColinKennedy/cursor-text-objects.nvim",
    config = function()
        vim.keymap.set(
            {"o", "x"},
            "[",
            "<Plug>(cursor-text-objects-up)",
            { desc = "Run from your current cursor to the end of the text-object." }
        )
        vim.keymap.set(
            {"o", "x"},
            "]",
            "<Plug>(cursor-text-objects-down)",
            { desc = "Run from your current cursor to the end of the text-object." }
        )
    end,
    version = "v1.*",
}
```

yields a bunch of submodule cloning errors:

```
  Failed (1)
    ○ cursor-text-objects.nvim 
        Cloning into '/home/thoma/.local/share/LazyVim/lazy/cursor-text-objects.nvim'...
        remote: Enumerating objects: 89, done.        
        remote: Counting objects: 100% (89/89), done.        
        remote: Compressing objects: 100% (74/74), done.        
        remote: Total 89 (delta 29), reused 56 (delta 9), pack-reused 0 (from 0)        
        Receiving objects: 100% (89/89), 15.71 KiB | 15.71 MiB/s, done.
        Resolving deltas: 100% (29/29), done.
        Submodule '.dependencies/busted' (git@github.com:LuaCATS/busted.git) registered for path '.dependencies/busted'
        Submodule '.dependencies/luassert' (git@github.com:LuaCATS/luassert.git) registered for path '.dependencies/luassert'
        Submodule '.dependencies/luvit-meta' (git@github.com:Bilal2453/luvit-meta.git) registered for path '.dependencies/luvit-meta'
        Cloning into '/home/thoma/.local/share/LazyVim/lazy/cursor-text-objects.nvim/.dependencies/busted'...
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
        fatal: clone of 'git@github.com:LuaCATS/busted.git' into submodule path '/home/thoma/.local/share/LazyVim/lazy/cursor-text-objects.nvim/.dependencies/busted' failed
        Failed to clone '.dependencies/busted'. Retry scheduled
        Cloning into '/home/thoma/.local/share/LazyVim/lazy/cursor-text-objects.nvim/.dependencies/luassert'...
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
        fatal: clone of 'git@github.com:LuaCATS/luassert.git' into submodule path '/home/thoma/.local/share/LazyVim/lazy/cursor-text-objects.nvim/.dependencies/luassert' failed
        Failed to clone '.dependencies/luassert'. Retry scheduled
        Cloning into '/home/thoma/.local/share/LazyVim/lazy/cursor-text-objects.nvim/.dependencies/luvit-meta'...
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
        fatal: clone of 'git@github.com:Bilal2453/luvit-meta.git' into submodule path '/home/thoma/.local/share/LazyVim/lazy/cursor-text-objects.nvim/.dependencies/luvit-meta' failed
        Failed to clone '.dependencies/luvit-meta'. Retry scheduled
        Cloning into '/home/thoma/.local/share/LazyVim/lazy/cursor-text-objects.nvim/.dependencies/busted'...
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
        fatal: clone of 'git@github.com:LuaCATS/busted.git' into submodule path '/home/thoma/.local/share/LazyVim/lazy/cursor-text-objects.nvim/.dependencies/busted' failed
        Failed to clone '.dependencies/busted' a second time, aborting
```

### Steps To Reproduce

See bug description.

### Expected Behavior

Plugin installs without errors

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
    {
        -- Add anything you need here (configuration, other plugins, etc)
        "ColinKennedy/cursor-text-objects.nvim",
    },
})
```

**Comment by CrimsonScholar** [comment]
What is the output of 

```sh
git clone git@github.com:LuaCATS/luassert.git .dependencies/luassert
git clone git@github.com:LuaCATS/busted.git .dependencies/busted
git clone git@github.com:Bilal2453/luvit-meta.git .dependencies/luvit-meta
```

If you don't have SSH keys set up then I would expect that above would fail.

**Comment by ColinKennedy** [comment]
What is the output of 

```sh
git clone git@github.com:LuaCATS/luassert.git .dependencies/luassert
git clone git@github.com:LuaCATS/busted.git .dependencies/busted
git clone git@github.com:Bilal2453/luvit-meta.git .dependencies/luvit-meta
```

If you don't have your SSH key set up for GitHub then I would expect that above would fail.

**Comment by cthoma** [comment]
First of all, I'm now able to enjoy your plugin. Good stuff!

Having a github account is not something I would expect when using a neovim plugin.
I already had my SSH key set up, but lazy.nvim still didn't allow cloning.

Then I tried you suggestion where I got

```
$ git clone git@github.com:LuaCATS/luassert.git .dependencies/luassert
Enter passphrase for /home/thoma/.ssh/id_ed25519:
```

This file can be created with `$ ssh-keygen -t ed25519 -C "some label text"`

I think lazy.nvim can't handle this "enter passphrase .." dialog and fails.

After some research I found that `ssh-agent` -- an SSH key manager -- can be used to prevent git from asking the passphrase.
For that I added `eval $(keychain --eval id_ed25519 >/dev/null)` to my `~/.zshrc`. `keychain` is a tool that deals with `ssh-agent` in ways I don't know but it works.

**Comment by ColinKennedy** [comment]
> This file can be created with $ ssh-keygen -t ed25519 -C "some label text"

I'm not sure how you set up your SSH but this is how I do it

```
ssh-keygen -b 4096
```

Press enter through all the prompts. Then copy the `~/.ssh/id_rsa.pub` to GitHub. It doesn't prompt for passwords after that.

> Having a github account is not something I would expect when using a neovim plugin

I agree with you however the submodules here only there to support `lua-languager-server` which currently requires them. I personally find that dependency not excusable so I put in an issue a while back basically asking "please remove the coupling between lua-language-server and git submodules" that didn't get a lot of attention. See https://github.com/LuaLS/lua-language-server/issues/2905. You're welcome to chat over there if you think raising this issue will be a good use case to explain why that's bad design. You have my vote at least :)

A workaround to all this could be to just delete the submodules entirely but keep the .gitmodules file. Basically, fake out `lua-language-server` into thinking that the folders are submodules even though they aren't. I confirmed that solution is viable over at https://github.com/jeffzi/llscheck/issues/7#issuecomment-2428194549 but would be very hacky.

An alternate would be to petition lazy.nvim and other package managers to have some kind of configuration option not to install submodules. e.g. something like

```lua
    "ColinKennedy/cursor-text-objects.nvim",
    config = function()
        vim.keymap.set(
            {"o", "x"},
            "[",
            "<Plug>(cursor-text-objects-up)",
            { desc = "Run from your current cursor to the end of the text-object." }
        )
        vim.keymap.set(
            {"o", "x"},
            "]",
            "<Plug>(cursor-text-objects-down)",
            { desc = "Run from your current cursor to the end of the text-object." }
        )
    end,
    submodules = false,
    version = "v1.*",
```

Though that's likely not to be a good idea because then every package manager would need its own equivalent.

**Comment by ColinKennedy** [comment]
Also @cthoma on a personal level you can also add `git config --global url."https://github.com/".insteadOf git@github.com:` to your `~/.gitconfig`.

The reason you were getting SSH errors I think is because the .gitmodules hard-codes the dependencies using SSH syntax. But with insteadOf, it will substitute all SSH URLs for their HTTPS variants. You would just need to move / remove the existing cursor-text-objects.nvim folder and do another rebuild. That has a good chance of working for your setup. Though of course something cleaner that could help everyone would be preferred.

**Comment by ColinKennedy** [comment]
@cthoma I think I fixed it - the `.dependencies` submodule directory is gone completely and tests still pass. Let me know if you still have issues cloning and I can re-address it!
